# -*- coding: utf-8 -*-
"""first python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bell6PJ1PI1fsonLO_RmF66UmsFmMe34

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0105EN-SkillsNetwork/labs/Module2/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Hands-on Lab: Create your Jupyter Notebook

#### Add your code below following the instructions given in the course

# Data Science Tools and Ecosystem

# In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:


*   Python
*   R
*   SQL

Some of the commonly used libraries used by Data Scientists include:

*   Numpy
*   Pandas
*   Matplotlib

| Data Science Tools |
|--------------------|
| Jupyter Notebook   |
| RStudio            |
| Spyder             |

###Below are a few examples of evaluating arithmetic expressions in Python
"""

#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

#This will convert 200 minutes to hours by diving by 60
200/60

"""##Author
Seddique Abbasi

**Objectives:**
unordered list:

*   Data Science Tools
*   Data Science Libraries
*   Arthimatic operations

Copyright ©2024 IBM Corporation. All rights reserved.
"""